"""Event-day scheduling model for F04.

`expanded/workload.py` measures the investigation makespan from authored
ticket estimates. This module wraps that simulation in the full event day:
facilitated segments (orientation, inject briefings, breaks, AAR) are modeled
explicitly and accounted SEPARATELY from investigation activity, per the F04
card and facilitator/assessment-aar.md.

Two questions the model answers:

1. Does the event fit the agreed window?  plan() lays out one event day and
   reports investigation vs facilitated time and whether the total lands in
   the target window (default 240-300 minutes, event decision 2026-09-17).
2. How sensitive is that to beginner pace?  sensitivity() rescales the
   authored 65-minute ticket allowance (a planning figure, not a measurement)
   and shows the makespan at each multiplier, so the organizer can see how
   much slower-than-planned beginner work the agenda absorbs before the
   investigation block overruns its allocation.

All numbers remain planning arithmetic until the beginner rehearsal replaces
them (see docs/rehearsal-worksheet.md).

Run from the repository root::

    PYTHONPATH=. python -m expanded.schedule --output docs/schedule-model.md
"""
import argparse
import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
from expanded.author import build
from expanded.workload import schedule as simulate

WINDOW_MIN, WINDOW_MAX = 240, 300
DEFAULT_TARGET = 270

# Facilitated segments around the investigation block. AAR and breaks are
# listed separately from investigation time by design (F04 acceptance).
DEFAULT_SEGMENTS = [
    {'id': 'orientation', 'title': 'Orientation and tool familiarization', 'minutes': 25,
     'kind': 'facilitated'},
    {'id': 'investigation', 'title': 'Investigation block (ticket work)', 'minutes': None,
     'kind': 'investigation'},
    {'id': 'inject-1', 'title': 'Inject briefing: late evidence release', 'minutes': 10,
     'kind': 'facilitated', 'during': 'investigation'},
    {'id': 'break', 'title': 'Break', 'minutes': 15, 'kind': 'break'},
    {'id': 'aar', 'title': 'After-action review', 'minutes': 30, 'kind': 'aar'},
]


def scaled_tickets(tickets, multiplier):
    """Return ticket dicts with estimate_minutes scaled by multiplier."""
    if multiplier <= 0:
        raise ValueError('multiplier must be positive')
    return [dict(t, estimate_minutes=max(1, round(int(t.get('estimate_minutes', 0)) * multiplier)))
            for t in tickets]


def plan(tickets, teams=10, multiplier=1.0, segments=None, target=DEFAULT_TARGET):
    """Lay out one event day.

    The investigation segment length equals the simulated makespan at the
    given pace multiplier; facilitated segments add their own minutes. The
    total is compared against the target and the 240-300 minute window.
    """
    if teams < 1:
        raise ValueError('teams must be positive')
    segments = DEFAULT_SEGMENTS if segments is None else segments
    investigation = simulate(scaled_tickets(tickets, multiplier), teams)['makespan']
    laid_out, total = [], 0
    for segment in segments:
        minutes = investigation if segment['kind'] == 'investigation' else int(segment['minutes'])
        laid_out.append(dict(segment, minutes=minutes))
        total += minutes
    facilitated = sum(s['minutes'] for s in laid_out if s['kind'] == 'facilitated')
    breaks = sum(s['minutes'] for s in laid_out if s['kind'] == 'break')
    aar = sum(s['minutes'] for s in laid_out if s['kind'] == 'aar')
    return {
        'teams': teams,
        'multiplier': multiplier,
        'target_minutes': target,
        'window': [WINDOW_MIN, WINDOW_MAX],
        'investigation_minutes': investigation,
        'facilitated_minutes': facilitated,
        'break_minutes': breaks,
        'aar_minutes': aar,
        'total_minutes': total,
        'segments': laid_out,
        'fits_window': WINDOW_MIN <= total <= WINDOW_MAX,
        'fits_target': abs(total - target) <= 15,
    }


def sensitivity(tickets, teams=10, multipliers=(1.0, 1.25, 1.5, 1.75, 2.0)):
    """Makespan and event-day fit at each pace multiplier."""
    return [plan(tickets, teams, m) for m in multipliers]


def render(plans, target=DEFAULT_TARGET):
    lines = [
        '# Event-day scheduling model (F04)',
        '',
        'Generated by `expanded/schedule.py`. Planning arithmetic, not a measurement; '
        'the beginner rehearsal replaces it (docs/rehearsal-worksheet.md). '
        'Facilitated segments, breaks and the AAR are accounted separately from '
        'investigation activity.',
        '',
        'Target window: %d-%d minutes (midpoint %d). Ten teams, one shared desktop each.'
        % (WINDOW_MIN, WINDOW_MAX, target),
        '',
        '## Agenda at authored pace (multiplier 1.0)',
        '',
        '| Segment | Kind | Minutes |',
        '|---|---|---|',
    ]
    base = plans[0]
    for segment in base['segments']:
        lines.append('| {title} | {kind} | {minutes} |'.format(**segment))
    lines += [
        '| **Total** | | **%d** |' % base['total_minutes'],
        '',
        'Investigation %d min; facilitated %d min; breaks %d min; AAR %d min. '
        'Fits window: %s.' % (base['investigation_minutes'], base['facilitated_minutes'],
                              base['break_minutes'], base['aar_minutes'],
                              'yes' if base['fits_window'] else 'NO'),
        '',
        '## Pace sensitivity',
        '',
        'The authored 65-minute ticket allowance is unmeasured. This table rescales it '
        'to show how beginner pace moves the investigation makespan and the event total.',
        '',
        '| Pace multiplier | Investigation makespan | Event total | Fits 240-300 |',
        '|---|---|---|---|',
    ]
    for entry in plans:
        lines.append('| %.2fx | %d | %d | %s |' % (
            entry['multiplier'], entry['investigation_minutes'], entry['total_minutes'],
            'yes' if entry['fits_window'] else 'NO'))
    lines += [
        '',
        'Reading: below 1.0x the event runs short (facilitated segments pad it); '
        'above ~1.4x the investigation block alone consumes the window and the agenda '
        'must shed facilitated time or accept overrun. The honest fix for a durable gap '
        'is more authored content (separate small content tasks), not agenda padding.',
        '',
    ]
    return '\n'.join(lines)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--teams', type=int, default=10)
    parser.add_argument('--target', type=int, default=DEFAULT_TARGET)
    parser.add_argument('--config', type=Path, default=Path('expanded/config.json'))
    parser.add_argument('--output', type=Path, default=Path('docs/schedule-model.md'))
    args = parser.parse_args()
    config = json.loads(args.config.read_text(encoding='utf-8')) if args.config.exists() else None
    tickets = build(config)
    plans = sensitivity(tickets, args.teams)
    args.output.write_text(render(plans, args.target), encoding='utf-8')
    print(json.dumps([{k: p[k] for k in ('multiplier', 'investigation_minutes',
                                         'total_minutes', 'fits_window')}
                      for p in plans], indent=2))


if __name__ == '__main__':
    main()
